const R = (globalThis as any).__kleff__?.React ?? {};
export const {
  createElement,
  Fragment,
  createContext,
  useContext,
  useState,
  useEffect,
  useRef,
  useMemo,
  useCallback,
  useReducer,
  useLayoutEffect,
  useId,
  forwardRef,
  memo,
  lazy,
  Suspense,
  Children,
  cloneElement,
  isValidElement,
  createRef,
  Component,
  PureComponent,
  StrictMode,
  startTransition,
  useTransition,
  useDeferredValue,
  useImperativeHandle,
  useSyncExternalStore,
  useInsertionEffect,
} = R;
export default R;
